# generated by datamodel-codegen:
#   filename:  http://localhost:8090/service/openapi.json
#   timestamp: 2026-04-22T20:07:38+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BalanceResponse(BaseModel):
    org_id: Annotated[str, Field(description="Organization ID", title="Org Id")]
    credit_balance_cents: Annotated[
        float,
        Field(
            description="Total available prepaid balance in cents (credits + prepaid commits). Always 0 when will_invoice is true.",
            title="Credit Balance Cents",
        ),
    ]
    pending_debit_balance_cents: Annotated[
        float | None,
        Field(
            description="Balance in cents currently held for inflight tasks plus charges not yet synced to the billing provider. Always 0 when will_invoice is true.",
            title="Pending Debit Balance Cents",
        ),
    ] = 0
    will_invoice: Annotated[
        bool | None,
        Field(
            description="True if this organization is billed by invoice (postpaid) rather than from a prepaid credit balance. Invoice-only orgs cannot add balance via this API.",
            title="Will Invoice",
        ),
    ] = False


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class CreateAppResponseModel(BaseModel):
    app_id: Annotated[str, Field(description="App ID", title="App Id")]


class AddBalanceRequest(BaseModel):
    amount_cents: Annotated[
        int,
        Field(
            description="Amount in cents to charge and add to the balance.",
            title="Amount Cents",
        ),
    ]
    idempotency_key: Annotated[
        str,
        Field(
            description="Required idempotency key. Stripe dedupes the charge server-side for at least 24h when the same key is submitted again for the same org (see https://docs.stripe.com/api/idempotent_requests). Pick a high-entropy value (e.g. a UUID) so distinct agent attempts do not collide.",
            max_length=128,
            min_length=1,
            title="Idempotency Key",
        ),
    ]


class CreateKeyResponse(BaseModel):
    api_key_id: Annotated[str, Field(description="API Key ID", title="Api Key Id")]
    api_key_name: Annotated[str, Field(description="API Key Name", title="Api Key Name")]
    app_id: Annotated[str, Field(description="App ID", title="App Id")]
    app_name: Annotated[str, Field(description="App Name", title="App Name")]
    created_by_user_id: Annotated[str, Field(description="Created by User ID", title="Created By User Id")]
    created_by_user_email: Annotated[str, Field(description="Created by User Email", title="Created By User Email")]
    display_value: Annotated[str, Field(description="Display Value", title="Display Value")]
    raw_api_key: Annotated[str | None, Field(description="Raw API Key", title="Raw Api Key")] = None
    created_at: Annotated[int, Field(description="Created At", title="Created At")]


class CreateApiKeyRequestModel(BaseModel):
    api_key_name: Annotated[str, Field(description="API Key Name", title="Api Key Name")]


class AppItem(BaseModel):
    app_name: Annotated[str, Field(description="App name", title="App Name")]
    org_name: Annotated[str | None, Field(description="Organization name", title="Org Name")]
    app_id: Annotated[str, Field(description="App ID", title="App Id")]
    org_id: Annotated[str, Field(description="Organization ID", title="Org Id")]


class CreateAppRequestModel(BaseModel):
    app_name: Annotated[str, Field(description="App name", title="App Name")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class GetAppsForOrgResponseModel(BaseModel):
    apps: Annotated[list[AppItem] | None, Field(description="List of apps", title="Apps")] = None
