# generated by datamodel-codegen:
#   filename:  http://localhost:8090/service/openapi.json
#   timestamp: 2026-04-22T00:34:17+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class CreateAppRequestModel(BaseModel):
    app_name: Annotated[str, Field(description="App name", title="App Name")]


class CreateKeyResponse(BaseModel):
    api_key_id: Annotated[str, Field(description="API Key ID", title="Api Key Id")]
    api_key_name: Annotated[str, Field(description="API Key Name", title="Api Key Name")]
    app_id: Annotated[str, Field(description="App ID", title="App Id")]
    app_name: Annotated[str, Field(description="App Name", title="App Name")]
    created_by_user_id: Annotated[str, Field(description="Created by User ID", title="Created By User Id")]
    created_by_user_email: Annotated[str, Field(description="Created by User Email", title="Created By User Email")]
    display_value: Annotated[str, Field(description="Display Value", title="Display Value")]
    raw_api_key: Annotated[str | None, Field(description="Raw API Key", title="Raw Api Key")] = None
    created_at: Annotated[int, Field(description="Created At", title="Created At")]


class CreateAppResponseModel(BaseModel):
    app_id: Annotated[str, Field(description="App ID", title="App Id")]


class CreateApiKeyRequestModel(BaseModel):
    api_key_name: Annotated[str, Field(description="API Key Name", title="Api Key Name")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class AppItem(BaseModel):
    app_name: Annotated[str, Field(description="App name", title="App Name")]
    org_name: Annotated[str | None, Field(description="Organization name", title="Org Name")]
    app_id: Annotated[str, Field(description="App ID", title="App Id")]
    org_id: Annotated[str, Field(description="Organization ID", title="Org Id")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class GetAppsForOrgResponseModel(BaseModel):
    apps: Annotated[list[AppItem] | None, Field(description="List of apps", title="Apps")] = None
